### ISSUE TITLE
Error if 'Package Destination Folderpath' is a UNC path 

### ISSUE THREAD

**Issue by patricjenni** [allenh-ni/nipm-feed-manager-gui-labview#2]
If one specifies a path to a feed in the UNC format, this results in errors.

Content of the file Feeds.ini

    [My App]
    Feed Folderpath = "\\server\my app"
    Package Destination Folderpath = "\\server\my app"

Package Destination Folderpath read by 'Read Feed INI.vi'
![read feed ini](https://user-images.githubusercontent.com/36151432/48408707-46fe7200-e73a-11e8-8841-fca0ff432a84.png)

**Comment by patricjenni** [comment]
Wanted to create a fork, but realized this project is implemented with LabVIEW 2014 and I only have LabVIEW 2016 installed...

This issue could be solved by setting the 'read raw string?' parameter to TRUE when reading the 'Package Destination Folderpath' key in the 'Read Feed INI.vi'. 

![read feed ini - bugfix](https://user-images.githubusercontent.com/36151432/48409152-5fbb5780-e73b-11e8-9e19-ce38c64663d1.png)

**Comment by eisenwr** [comment]
This appears to be fixed in 2.3.0.17. I had come across the same issue and fix. I believe using the Path key type would be a more robust option than the String key type.

**Comment by allenh-ni** [comment]
Fixed issue in NIPM Feed Manager v2.3.0.17
Fixed bug in the Read Feed INI subVI, as described in this issue.
